capability:
  #命令超时时间 单位秒
  newCommandTimeout: 120
  #最大运行时间 单位分钟
  runTime: 1800
androidCapability:
  appPackage: "com.ymatou.shop"
  appActivity: ".ui.activity.SplashActivity"
  logCmd: "adb -s #udid# logcat -b main -b system -b events -b radio *:D | grep com.ymatou.shop"
  deviceNames:
    #模拟器
    - deviceName: "127.0.0.1:62001"
      platformVersion: "4.4.2"
      #app: ""
      appium: "http://127.0.0.1:4723/wd/hub"
    #荣耀8
    - deviceName: "NXTDU16B05010871"
      platformVersion: "7.0"
      #aapp: ""
      appium: "http://127.0.0.1:4723/wd/hub"
    #vivo
    - deviceName: "94fabcfa"
      platformVersion: "5.1.1"
      #app: ""
      appium: "http://127.0.0.1:4723/wd/hub"
   #xiaomi
    - deviceName: "INMN8TDIK7QKH6EI"
      platformVersion: "6.0"
      #app: ""
      appium: "http://127.0.0.1:4723/wd/hub"
   #锤子
    - deviceName: "2bad9d02"
      platformVersion: "5.1.1"
      #app: ""
      appium: "http://127.0.0.1:4723/wd/hub"
iosCapability:
  deviceName: "iPhone (3)"
  logCmd: "idevicesyslog -d -u d36d600b4ece53a8bde8daf869790012a46842c3 |grep 'iPhone Buyer'"
  bundleId: "com.ymatou.Shopping"
  udid: "d36d600b4ece53a8bde8daf869790012a46842c3"
  platformVersion: "9.3.1"
  autoAcceptAlerts: "true"
  appium: "http://127.0.0.1:4723/wd/hub"